"""price field fix trying

Revision ID: 8127279a50b1
Revises: 878fec580e7c
Create Date: 2023-06-03 12:38:55.891928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8127279a50b1'
down_revision = '878fec580e7c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipt_items', sa.Column('price', sa.Numeric(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('receipt_items', 'price')
    # ### end Alembic commands ###
