"""creating receipts

Revision ID: 878fec580e7c
Revises: 9f638602f011
Create Date: 2023-06-02 15:55:39.290232

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '878fec580e7c'
down_revision = '9f638602f011'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('receipt_id', sa.Integer(), nullable=False),
    sa.Column('user_id_fk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id_fk'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('receipt_id')
    )
    op.create_table('receipt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_id_fk', sa.Integer(), nullable=False),
    sa.Column('product_id_fk', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_id_fk'], ['products.product_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id_fk'], ['receipts.receipt_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('receipt_items')
    op.drop_table('receipts')
    # ### end Alembic commands ###
